#!/usr/bin/env python3

import re
import os
import ffmpeg


def convert_directory(input_dir: str, output_name: str):
    """
    Takes a directory full of images, and converts them into a video file at a given location with a given name.

    Args:
        input_dir (str): the input directory to be converted. The images inside the directory are named ~strname_%04d.png~. This includes ~01234567_012345_%04d.png~ and ~output_%04d.png~. This is guaranteed.
        output_name (str): the name of the file (with extension) that is generated by combining the images. An example is ~test/sample_output.mp4~.

    Returns:
        Nothing. The file should be written to disk.
        Unless there's an error. In which case, it returns -1.

    Hints:
    - This is my solution.
    Precondition: ~test/images~ is filled with images like ~02032021_221508_2108.png~. There should be 3599 files.
    Postcondition: ~sample_output.mp4~ is created inside the ~test~ directory, and is a video of the Aurora Borealis on a clear night. It should be 25 frames per second, 2:23-4 long, and about 11 MB in size.
    """
    # sanity checks
    if os.path.exists(output_name):
        print(f"Warning: {output_name} exists. Deleting {output_name}.")
        os.remove(output_name)
    if not os.path.exists(input_dir):
        print(f"Error: {input_dir} does not exist.")
        return -1
    files = os.listdir(input_dir)
    if len(files) == 0:
        print(
            f"Error: {input_dir} is empty. Did everything go alright? Is {input_dir} the correct directory?"
        )
        return -1

    match = re.match(r"(\w+)_(\d+)\.png", files[0])
    stem = match.group(1)
    # print(stem)
    ffmpeg.input(os.path.join(input_dir, stem + "_%04d.png")).output(
        output_name, framerate=25
    ).run()


if __name__ == "__main__":
    convert_directory(
        os.path.join("test", "images"), os.path.join("test", "sample_output.mp4")
    )
