#!/usr/bin/env python3

import re
import os
import ffmpeg


def convert_directory(input_dir: str, output_name: str):
    """
    Takes a directory full of images, and converts them into a video file at a given location with a given name.

    Args:
        input_dir (str): the input directory to be converted. The images inside the directory are named ~strname_%04d.png~. This includes ~01234567_012345_%04d.png~ and ~output_%04d.png~. This is guaranteed.
        output_name (str): the name of the file (with extension) that is generated by combining the images. An example is ~test/sample_output.mp4~.

    Returns:
        Nothing. The file should be written to disk.

    Hints:
    - The files are structured such that ~%04d~ is the frame number of the video, specified to four digits. For an example, see ~test/images~.
    - Regular expressions (regex, re) are your friend for finding the string stem separate from the frame number. Since I do not want you to learn regex syntax, I'll give you the regex:
    #+begin_src: python
    r"(\w+)_(\d+)\.png"
    #+end_src
      - If you want to learn regex, explain what this regex does, and why it works for both sample strings.
    - Use re.match() to get a match object, and match.groups() to get the base name separate from the frame number.
    - ~ffmpeg~ will take an input and convert to the output. For example, the terminal command ~ffmpeg -i foo.mp4 -o bar.mov~ will take ~foo.mp4~ and convert it into ~bar.mov~.
      - ~ffmpeg~ can convert image directories into videos using ~ffmpeg -i location%04d.png bar.mp4~ to turn all images with the name ~location0001~ (and so on) into an mp4 file.
      - For an example of how ffmpeg in Python is used, see ~test.py~.
    - I do not believe you need to use any loops.
    - ~ffmpeg~ will automatically write the output to disk at the location.
    - Make sure FFmpeg is installed on your system. Since you're on a Mac, you will probably have to install Homebrew, and then ~brew install ffmpeg~.
    - WRITE OUT YOUR PSEUDOCODE FIRST. Then, write it in Python.

    Precondition: ~test/images~ is filled with images like ~02032021_221508_2108.png~. There should be 3599 files.
    Postcondition: ~sample_output.mp4~ is created inside the ~test~ directory, and is a video of the Aurora Borealis on a clear night. It should be 25 frames per second, 2:23-4 long, and about 11 MB in size.
    """
    print("Error: needs to be implemented")
    return -1


if __name__ == "__main__":
    convert_directory(
        os.path.join("test", "images"), os.path.join("test", "sample_output.mp4")
    )
